# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recorder.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(482, 382)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget.setGeometry(QtCore.QRect(90, 20, 321, 200))
        self.openGLWidget.setObjectName("openGLWidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(90, 250, 111, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(280, 250, 151, 101))
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 250, 61, 21))
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 300, 71, 31))
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 250, 151, 101))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 300, 113, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2.raise_()
        self.openGLWidget.raise_()
        self.comboBox.raise_()
        self.pushButton.raise_()
        self.label.raise_()
        self.label_5.raise_()
        self.lineEdit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ScreenRecorder"))
        self.comboBox.setCurrentText(_translate("MainWindow", "640x480"))
        self.comboBox.setItemText(0, _translate("MainWindow", "640x480"))
        self.comboBox.setItemText(1, _translate("MainWindow", "800x600"))
        self.comboBox.setItemText(2, _translate("MainWindow", "1024x768"))
        self.comboBox.setItemText(3, _translate("MainWindow", "1280x720"))
        self.comboBox.setItemText(4, _translate("MainWindow", "1280x800"))
        self.comboBox.setItemText(5, _translate("MainWindow", "1280x1024"))
        self.comboBox.setItemText(6, _translate("MainWindow", "1360x768"))
        self.comboBox.setItemText(7, _translate("MainWindow", "1366x768"))
        self.comboBox.setItemText(8, _translate("MainWindow", "1440x900"))
        self.comboBox.setItemText(9, _translate("MainWindow", "1536x864"))
        self.comboBox.setItemText(10, _translate("MainWindow", "1600x900"))
        self.comboBox.setItemText(11, _translate("MainWindow", "1600x1200"))
        self.comboBox.setItemText(12, _translate("MainWindow", "1680x1050"))
        self.comboBox.setItemText(13, _translate("MainWindow", "1920x1080"))
        self.pushButton.setText(_translate("MainWindow", "Start Recording"))
        self.label.setText(_translate("MainWindow", "Resolution"))
        self.label_5.setText(_translate("MainWindow", "Record Name"))
        self.pushButton_2.setText(_translate("MainWindow", "Stop Recording"))
